<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Suchita-PC" ignored="0" name="Log Verification Test Cases" tests="4" failures="3" timestamp="20 Jun 2018 09:30:06 GMT" time="0.111" errors="0">
  <testcase name="smallResposeTest" time="0.02" classname="com.apachelog.qa.test.LogVerificationTest">
    <failure type="java.lang.AssertionError" message="Total 9 Number of response size is greater than 100000 byte in given log. Check Reporter Output for more info expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Total 9 Number of response size is greater than 100000 byte in given log. Check Reporter Output for more info expected [true] but found [false]
at com.apachelog.qa.test.LogVerificationTest.smallResposeTest(LogVerificationTest.java:59)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- smallResposeTest -->
  <testcase name="authorizedAccessTest" time="0.006" classname="com.apachelog.qa.test.LogVerificationTest"/>
  <testcase name="putBeforePostTest" time="0.01" classname="com.apachelog.qa.test.LogVerificationTest">
    <failure type="java.lang.AssertionError" message="Failure Reason may be either of two.1) PUT to a given path observed after POST to a given path for one or more times in given log. 2) NO PUT Requset in log for POST request to a given path. For more Details Please refer Reporter Output log in TestNG Report expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failure Reason may be either of two.1) PUT to a given path observed after POST to a given path for one or more times in given log. 2) NO PUT Requset in log for POST request to a given path. For more Details Please refer Reporter Output log in TestNG Report expected [true] but found [false]
at com.apachelog.qa.test.LogVerificationTest.putBeforePostTest(LogVerificationTest.java:101)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- putBeforePostTest -->
  <testcase name="suspiciousActivityTest" time="0.002" classname="com.apachelog.qa.test.LogVerificationTest">
    <failure type="java.lang.AssertionError" message="Count for 401 staus code in given log is greater than 4.
 Actual is :122 Expected is less than : 5 expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Count for 401 staus code in given log is greater than 4.
 Actual is :122 Expected is less than : 5 expected [false] but found [true]
at com.apachelog.qa.test.LogVerificationTest.suspiciousActivityTest(LogVerificationTest.java:119)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- suspiciousActivityTest -->
</testsuite> <!-- Log Verification Test Cases -->
