<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Suchita-PC" ignored="0" name="Log Verification Test Cases" tests="4" failures="3" timestamp="20 Jun 2018 13:03:13 GMT" time="0.078" errors="0">
  <testcase name="smallResposeTest" time="0.006" classname="com.apachelog.qa.test.LogVerificationTest"/>
  <testcase name="authorizedAccessTest" time="0.005" classname="com.apachelog.qa.test.LogVerificationTest">
    <failure type="java.lang.AssertionError" message="Total 2 401 found from site ***.example.org . Failed to feed Rover. For detailed logs and information Please refer Reporter output log in TestNG report expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Total 2 401 found from site ***.example.org . Failed to feed Rover. For detailed logs and information Please refer Reporter output log in TestNG report expected [true] but found [false]
at com.apachelog.qa.test.LogVerificationTest.authorizedAccessTest(LogVerificationTest.java:77)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- authorizedAccessTest -->
  <testcase name="putBeforePostTest" time="0.001" classname="com.apachelog.qa.test.LogVerificationTest">
    <failure type="java.lang.AssertionError" message="Failure Reason may be either of two.1) PUT to a given path observed after POST to a given path for one or more times in given log. 2) NO PUT Requset in log for POST request to a given path. For more Details Please refer Reporter Output log in TestNG Report expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failure Reason may be either of two.1) PUT to a given path observed after POST to a given path for one or more times in given log. 2) NO PUT Requset in log for POST request to a given path. For more Details Please refer Reporter Output log in TestNG Report expected [true] but found [false]
at com.apachelog.qa.test.LogVerificationTest.putBeforePostTest(LogVerificationTest.java:94)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- putBeforePostTest -->
  <testcase name="suspiciousActivityTest" time="0.001" classname="com.apachelog.qa.test.LogVerificationTest">
    <failure type="java.lang.AssertionError" message="Count for 401 staus code in given log is greater than 4.
 Actual is :9 Expected is less than : 5 expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Count for 401 staus code in given log is greater than 4.
 Actual is :9 Expected is less than : 5 expected [false] but found [true]
at com.apachelog.qa.test.LogVerificationTest.suspiciousActivityTest(LogVerificationTest.java:112)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- suspiciousActivityTest -->
</testsuite> <!-- Log Verification Test Cases -->
